### 错误／调试／ 测试

- 错误处理 `try...except…finally`

- 调试  

  - print 

  - ```python
    # 断言
    assert n != 0, 'n is zero!'
    # 表达式n != 0应该是True，否则，后面的代码就会出错。
    # 如果断言失败，assert语句本身就会抛出AssertionError：n is zero!
    ```

  - ```python
    logging.info('n = %d' % n)
    import logging
    logging.basicConfig(level=logging.INFO)
    # debug，info，warning，error等几个level
    ```

- 单元测试

  对一个模块、一个函数或者一个类来进行正确性检验的测试工作 

  ```python
  # mydict.py
  class Dict(dict):

      def __init__(self, **kw):
          super(Dict, self).__init__(**kw)

      def __getattr__(self, key):
          try:
              return self[key]
          except KeyError:
              raise AttributeError(r"'Dict' object has no attribute '%s'" % key)

      def __setattr__(self, key, value):
          self[key] = value
          
  # mydict_test.py
  import unittest

  from mydict import Dict

  class TestDict(unittest.TestCase):

      def test_init(self):
          d = Dict(a=1, b='test')
          self.assertEquals(d.a, 1)
          self.assertEquals(d.b, 'test')
          self.assertTrue(isinstance(d, dict))

      def test_key(self):
          d = Dict()
          d['key'] = 'value'
          self.assertEquals(d.key, 'value')

      def test_attr(self):
          d = Dict()
          d.key = 'value'
          self.assertTrue('key' in d)
          self.assertEquals(d['key'], 'value') # 判断是否相等

      def test_keyerror(self):
          d = Dict()
          with self.assertRaises(KeyError):
              value = d['empty']

      def test_attrerror(self):
          d = Dict() # 想要抛出xx类型的错误
          with self.assertRaises(AttributeError):
              value = d.empty
              
  ## 运行方式1
  if __name__ == '__main__':
      unittest.main()
  # python mydict_test.py 运行

  ## 运行方式2
  # python -m unittest mydict_test
  ```

  两个特殊的`setUp()`和`tearDown()`方法，分别在每调用一个测试方法的前后分别被执行，将在每一个测试方法中重复的代码提出来

- 文档测试 doctest

  命令行运行 ／ 作为示例代码

测试驱动开发 TDD：Test-Driven Development